[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/saas/*"
  to = "https://api.tekton.co.kr/api/saas/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
